<%@ Page Language="C#" AutoEventWireup="true" CodeFile="lll.aspx.cs" Inherits="lll" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
    <title></title>
<head runat="server">
 
  
</head>

<body>
    <form id="form1" runat="server">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <asp:GridView ID="GridView1" runat="server">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </asp:GridView>
    </form>
</body>
</html>
